<?php 

return [
    'schedules' => 'Planifications',
    'manage-schedules' => 'Gérer les planifications',
    'create-schedule' => 'Créer une planification',
    'name' => 'Nom',
    'last-run-at' => 'Dernière exécution',
    'next-run-at' => 'Prochaine exécution',
    'status' => 'Statut',
    'active' => 'Actif',
    'inactive' => 'Inactif',
    'processing' => 'En cours',
    'manage-schedule' => 'Gérer la planification',
    'new-task' => 'Nouvelle tâche',
    'run-now' => 'Exécuter maintenant',
    'editBtn' => 'Modifier',
    'n/a' => 'n/a',
    'never' => 'jamais',

    'no-schedules' => 'Aucune planification n\'est configurée pour ce serveur.',
    'ignore-files-folders' => 'Fichiers et dossiers ignorés',
    'continues-on-failure' => 'Continue en cas d\'échec',
    'later' => 'plus tard',

    'minute' => 'Minute',
    'hour' => 'Heure',
    'day' => 'Jour',
    'week' => 'Semaine',
    'day-of-month' => 'Jour du mois',
    'month' => 'Mois',
    'day-of-week' => 'Jour de la semaine',

    'deleteTask' => [
        'title' => 'Confirmer la suppression de la tâche',
        'description' => 'Êtes-vous sûr de vouloir supprimer cette tâche ? Cette action est irréversible.',
        'delete' => 'Supprimer la tâche'
    ],
    'delete' => [
        'title' => 'Supprimer la planification',
        'description' => 'Toutes les tâches seront supprimées et les processus en cours seront arrêtés.',
        'delete' => 'Supprimer'
    ],
    'edit' => [
        'title-1' => 'Modifier la planification',
        'title-2' => 'Créer une nouvelle planification',

        'description' => 'Le système de planification prend en charge la syntaxe Cron pour définir quand les tâches doivent être exécutées. Utilisez les champs ci-dessus pour définir les horaires.',

        'name' => 'Nom de la planification',
        'name-description' => 'Un identifiant lisible pour cette planification.',
        'cheatsheet' => 'Afficher la fiche',
        'cheatsheet-description' => 'Afficher la fiche Cron avec des exemples',
        'online-when-online' => 'Uniquement lorsque le serveur est en ligne',
        'online-when-online-description' => 'Exécuter cette planification uniquement si le serveur est en cours d\'exécution.',
        'enabled' => 'Planification activée',
        'enabled-description' => 'Cette planification sera exécutée automatiquement si elle est activée.',

        'easy-mode' => 'Mode simple',
        'easy-mode-description' => 'Passer en mode avancé pour une configuration Cron personnalisée',
        'easy' => 'Simple',
        'advanced' => 'Avancé',

        'save-changes' => 'Enregistrer les modifications',
    ],
    'cheatsheet' => [
        'example' => 'Exemples',
        'every-5-minutes' => 'toutes les 5 minutes',
        'every-hour' => 'toutes les heures',
        'hour-range' => 'plage horaire',
        'once-a-day' => 'une fois par jour',
        'every-monday' => 'chaque lundi',
        'special-characters' => 'Caractères spéciaux',
        'any-value' => 'toute valeur',
        'value-list-separator' => 'séparateur de liste de valeurs',
        'range-values' => 'valeurs de plage',
        'step-values' => 'valeurs par pas',
    ],
    'task' => [
        'message' => 'Une tâche de sauvegarde ne peut pas être créée lorsque la limite de sauvegarde du serveur est définie à 0.',
        'edit-task' => 'Modifier la tâche',
        'save-changes' => 'Enregistrer les modifications',
        'create-task' => 'Créer une tâche',
        'action' => 'Action',
        'send-command' => 'Envoyer une commande',
        'send-power-action' => 'Envoyer une action d\'alimentation',
        'create-backup' => 'Créer une sauvegarde',
        'discord-webhook' => 'Webhook Discord',
        'delete-files' => 'Supprimer des fichiers',
        'files-and-folders' => 'Fichiers et dossiers',
        'one-path-per-line' => 'Un chemin par ligne. Les chemins sont relatifs à la racine du serveur, par exemple logs ou logs/example.yml',
        'offset' => 'Décalage (en secondes)',
        'offset-description' => 'Temps d\'attente après la tâche précédente avant exécution. Ignoré pour la première tâche.',
        'payload' => 'Charge utile',
        'ignored-files' => 'Fichiers ignorés',
        'ignored-files-description' => 'Optionnel. Inclure les fichiers et dossiers à exclure de la sauvegarde. Par défaut, le fichier .pteroignore est utilisé. Si la limite est atteinte, la sauvegarde la plus ancienne sera supprimée.',
        'start-server' => 'Démarrer le serveur',
        'stop-server' => 'Arrêter le serveur',
        'restart-server' => 'Redémarrer le serveur',
        'kill-server' => 'Forcer l\'arrêt du serveur',
        'continue-on-failure' => 'Continuer en cas d\'échec',
        'continue-on-failure-description' => 'Les tâches suivantes seront exécutées même si celle-ci échoue.',
    ],
];
