<?php

return [
    'online' => 'En ligne',
    'offline' => 'Hors ligne',
    'starting' => 'Démarrage',
    'stopping' => 'Arrêt',
    'suspended' => 'Suspendu',
    'connection-error' => 'Erreur de connexion',
    'transferring' => 'Transfert',
    'installing' => 'Installation',
    'restoring-backup' => 'Restauration de sauvegarde',
    'unavailable' => 'Indisponible',
    'status' => 'Statut',
    'CPU' => 'CPU',
    'memory' => 'RAM',
    'disk' => 'Disque',
    'unlimited' => 'Illimité',
    'start' => 'Démarrer',
    'restart' => 'Redémarrer',
    'stop' => 'Arrêter',
    'kill' => 'Forcer l\'arrêt',
    'forcibly-stop-process' => 'Forcer l\'arrêt du processus',
    'continue' => 'Continuer',
    'forcibly-stopping-alert' => 'Forcer l\'arrêt d\'un serveur peut entraîner une corruption des données.',
    'cpu-usage' => 'Utilisation du CPU',
    'memory-usage' => 'Utilisation de la RAM',
    'disk-usage' => 'Utilisation du disque',
    'inbound-outbound' => 'Entrant / Sortant',
    'low-resources' => 'Ressources faibles',
    'low-resources-desc' => 'Votre serveur manque de ressources, pensez à améliorer votre offre',
    'upgrade-server' => 'Améliorer le serveur',
    'cancel' => 'Annuler',
    'copied-text' => 'Le texte "{{text}}" à été copié dans le presse-papiers.',
    'showing' => 'Affichage',
    'to' => 'à',
    'of' => 'sur',
    'results' => 'résultats.',
];
